# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2025-2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Plugin build macOS

# file: .github/workflows/plugin-build-macos.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-06-21

on:
  workflow_call:
    inputs:
      job-index:
        description: The job index for logging.
        required: false
        type: number
        default: 0
      environment:
        description: The environment name for the build jobs, or empty string for no environment.
        required: false
        type: string
        default: ''
      runs-on:
        description: The runner label to run this workflow on.
        required: true
        type: string
      DEVELOPER_DIR:
        description: The value of DEVELOPER_DIR environment variable.
        required: true
        type: string
      OSX_ARCHITECTURES:
        description: The architecture to build for.
        required: true
        type: string
      OSX_DEPLOYMENT_TARGET:
        description: The deployment target of macOS.
        required: true
        type: string
      VCPKG_BINARY_SOURCES:
        description: VCPKG_BINARY_SOURCES environment variable for the build jobs.
        required: true
        type: string

    secrets:
      APP_STORE_CONNECT_ISSUER:
        required: false
      APP_STORE_CONNECT_KEY:
        required: false
      APP_STORE_CONNECT_KEY_ID:
        required: false
      MACOS_SIGNING_APPLICATION_IDENTITY:
        required: false
      MACOS_SIGNING_CERT_PASSWORD:
        required: false
      MACOS_SIGNING_CERT:
        required: false
      MACOS_SIGNING_INSTALLER_IDENTITY:
        required: false

permissions: {}

jobs:
  build-macos-universal:
    environment: ${{ inputs.environment }}
    runs-on: macos-15
    timeout-minutes: 180

    permissions:
      contents: read

    env:
      DEVELOPER_DIR: '${{ inputs.DEVELOPER_DIR }}'
      OSX_ARCHITECTURES: '${{ inputs.OSX_ARCHITECTURES }}'
      OSX_DEPLOYMENT_TARGET: '${{ inputs.OSX_DEPLOYMENT_TARGET }}'
      VCPKG_BINARY_SOURCES: '${{ inputs.VCPKG_BINARY_SOURCES }}'

    steps:
      - name: Print Xcode version
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          xcodebuild -version

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Extract buildspec.props
        id: buildspec
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          awk '!/(^#|^[[:space:]]*$)/' buildspec.props >> "$GITHUB_OUTPUT"

      - name: Checkout vcpkg
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/vcpkg
          ref: ${{ steps.buildspec.outputs.vcpkg_default_git_tag }}
          persist-credentials: false
          path: vcpkg
          filter: blob:none

      - name: Run bootstrap-vcpkg.sh
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Checkout obs-studio
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: obsproject/obs-studio
          ref: ${{ steps.buildspec.outputs.obs_studio_git_tag }}
          persist-credentials: false
          path: obs-studio
          filter: blob:none

      - name: Build OBS (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
        run: |
          PWSH_EXE="$("$VCPKG_ROOT/vcpkg" fetch powershell-core | tail -n1)"
          CMAKE_EXE="$("$VCPKG_ROOT/vcpkg" fetch cmake | tail -n1)"

          pwsh() {
            env -i \
              DEVELOPER_DIR="$DEVELOPER_DIR" \
              HOME="$HOME" \
              PATH="${PWSH_EXE%/*}:${CMAKE_EXE%/*}:/usr/bin:/bin:/usr/sbin:/sbin" \
              PLUGIN_BUILD_DIR="$GITHUB_WORKSPACE" \
              "$PWSH_EXE" "$@"
          }

          pwsh -NoProfile -Command "Import-Module ./scripts/BuildOBS.psm1; Initialize-ObsDeps -Component prebuilt"
          pwsh -NoProfile -Command "Import-Module ./scripts/BuildOBS.psm1; Initialize-ObsDeps -Component qt6"
          pwsh -NoProfile -Command "Import-Module ./scripts/BuildOBS.psm1; Invoke-ObsConfigure"
          pwsh -NoProfile -Command "Import-Module ./scripts/BuildOBS.psm1; Invoke-ObsBuild" | tee build_obs_release.log | xcbeautify
          pwsh -NoProfile -Command "Import-Module ./scripts/BuildOBS.psm1; Install-Obs"

      - name: Upload OBS build logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build OBS logs
          path: |
            build_obs*.log
          if-no-files-found: ignore
          retention-days: 7

      - name: Build Plugin (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
        run: |
          CMAKE_EXE="$("$VCPKG_ROOT/vcpkg" fetch cmake | tail -n1)"

          cmake() {
            env -i \
              DEVELOPER_DIR="$DEVELOPER_DIR" \
              HOME="$HOME" \
              PATH="${CMAKE_EXE%/*}:/usr/bin:/bin:/usr/sbin:/sbin" \
              "$CMAKE_EXE" "$@"
          }

          cmake --preset macos -G Xcode -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build --preset macos --config RelWithDebInfo | tee build_plugin_macos.log | xcbeautify

      - name: Upload Plugin build logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build Plugin logs
          path: |
            build_plugin_*.log
          if-no-files-found: ignore
          retention-days: 7

      - name: Install Plugin (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          cmake --install build --config RelWithDebInfo --strip --prefix build_stage

      - name: Extract dSYM
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          mkdir -p release
          . ./build/cmake_export.sh

          dsymutil "build/RelWithDebInfo/$PLUGIN_NAME.plugin/Contents/MacOS/$PLUGIN_NAME" -o "build/$PLUGIN_NAME.dSYM"
          ZSTD_CLEVEL=19 tar -acf "release/$PLUGIN_NAME.dSYM.tar.zst" --mac-metadata "build/$PLUGIN_NAME.dSYM"

      - name: Set up macOS Signing Certificates
        if: inputs.environment == 'production-macos'
        id: codesign
        uses: ./.github/actions/setup-macos-codesigning
        with:
          MACOS_SIGNING_APPLICATION_IDENTITY: ${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}
          MACOS_SIGNING_CERT: ${{ secrets.MACOS_SIGNING_CERT }}
          MACOS_SIGNING_CERT_PASSWORD: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}

      - name: Package Plugin (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CODESIGN_ENABLED: "${{ inputs.environment == 'production-macos' }}"
          MACOS_SIGNING_APPLICATION_IDENTITY: ${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}
          MACOS_SIGNING_INSTALLER_IDENTITY: ${{ secrets.MACOS_SIGNING_INSTALLER_IDENTITY }}
        run: |
          mkdir -p release
          . ./build/cmake_export.sh

          PLUGIN_BUNDLE="build_stage/Library/Application Support/obs-studio/plugins/$PLUGIN_NAME.plugin"

          if [[ "$CODESIGN_ENABLED" == true ]]; then
            codesign -s "$MACOS_SIGNING_APPLICATION_IDENTITY" -f --deep --options runtime --timestamp "$PLUGIN_BUNDLE"
          fi

          pkgbuild \
            --root build_stage \
            --identifier "$PLUGIN_BUNDLE_ID" \
            --version "$PLUGIN_VERSION" \
            --install-location / \
            build/component.pkg

          if [[ "$CODESIGN_ENABLED" == true ]]; then
            productbuild \
              --distribution build/Distribution \
              --package-path build \
              --resources . \
              --sign "$MACOS_SIGNING_INSTALLER_IDENTITY" \
              "release/$PLUGIN_NAME-$PLUGIN_VERSION-macos-universal.pkg"
          else
            productbuild \
              --distribution build/Distribution \
              --package-path build \
              --resources . \
              "release/$PLUGIN_NAME-$PLUGIN_VERSION-macos-universal.pkg"
          fi

      - name: Notarize Installer
        if: inputs.codesign-enabled
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          BASH_ENV: '${{ env.CLEAN_BASH_ENV }}'
          PATH: '${{ env.FILTERED_PATH }}'
          KEEP_ENV_VARS: 'APP_STORE_CONNECT_ISSUER;APP_STORE_CONNECT_KEY;APP_STORE_CONNECT_KEY_ID'
          APP_STORE_CONNECT_ISSUER: ${{ secrets.APP_STORE_CONNECT_ISSUER }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        run: |
          KEY_FILE="$(mktemp -t APP_STORE_CONNECT_KEY)"

          printenv APP_STORE_CONNECT_KEY >"$KEY_FILE"

          xcrun notarytool submit ./release/*-macos-universal.pkg \
            --issuer "${APP_STORE_CONNECT_ISSUER}" \
            --key "$KEY_FILE" \
            --key-id "${APP_STORE_CONNECT_KEY_ID}" \
            --wait

          xcrun stapler staple ./release/*-macos-universal.pkg

      - name: Upload Plugin Binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pluginbinary-${{ runner.os }}-universal-${{ github.run_id }}
          path: |
            release/*.pkg
            release/*.dSYM.tar.zst
          if-no-files-found: error
          retention-days: 7
